from sqlalchemy.orm import Session # type hint for the database session
from fastapi import HTTPException # used to send error responses to the client

from models.product import Product # Product table model
from models.sale import Sale # Sale table model
from models.sale_item import SaleItem # SaleItem table model
from schemas.sale import SaleCreate # the expected input shape for sale

def create_sale_with_stock_update(db: Session, sale_data: SaleCreate) -> Sale:  #this function handles the full sale process - validation, creation, stock reduction
    
    total = 0.0 # will accumulate the total sale amount
    items_to_create = [] # temporary list to hold validated items before saving
    
    # STEP 1 - validate every time BEFORE touching the database
    for item in sale_data.items: # loop through each product in the sale
        product = db.query(Product).filter(Product.id == item.product_id).first() # find the product in DB
        
        if not product: # if product doesn't exist, stop everything
            raise HTTPException(
                status_code=404, # not found error
                detail=f"Product with id {item.product_id} not found."  #helpful error message
            )
        
        if product.stock < item.quantity: # if not enough stock, stop everything
            raise HTTPException(
                status_code=400, # bad request error
                detail=f"Not enough stock for '{product.name}'. "
                f"Available: {product.stock}, Requested: {item.quantity}" # tell user what's wrong
            )
            
        subtotal = product.price * item.quantity # calculate cost for this product line
        total += subtotal # add to running total
        items_to_create.append((product, item.quantity, product.price)) # store for later saving
            
    # STEP 2 - create the Sale record in the database
    sale = Sale(total_amount=round(total, 2)) # create sale with rounded total
    db.add(sale) # stage the sale for saving
    db.flush() # get the sale.id generated by DB withouth fully committing yet
    
    # STEP 3 - create each SaleItem and reduce product stock
    for product, quantity, unit_price in items_to_create: # loop through validated items
        sale_item = SaleItem(    #create a new sale item record
            sale_id=sale.id,  # link to the parent sale
            product_id=product.id, # link to the product
            quantity=quantity, # how many were sold
            unit_price=unit_price # price at time of sale (important - price may change later)
        )
        db.add(sale_item) # stage sale item for saving
        product.stock -= quantity # reduce the product stock automatically
        
    db.commit() # save everything to the database at once
    db.refresh(sale) # reload sale from DB to get all updated fields
    return sale # send back the completed sale 
         